Repository nervosnetwork/muta, pull requests merged in 2020-07, with the labels that each got.

#332 chore: Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: size/M

#335 chore: Update CI pipeline
  jenkins-x-ci.yml
  jenkins-x-e2e.yml
  jenkins-x.yml
Labels: do-not-merge/work-in-progress, size/M

#336 chore: Fix ci
  Makefile
  devtools/docker-build/Dockerfile.CI
  devtools/docker-build/Dockerfile.e2e-env
  jenkins-x-clippy.yml
  jenkins-x-e2e.yml
  jenkins-x-fmt.yml
  jenkins-x-unit.yml
  jenkins-x.yml
Labels: approved, ok-to-test, size/L

#337 refactor(auth): change verified map to array
  built-in-services/authorization/Cargo.toml
  built-in-services/authorization/src/lib.rs
  built-in-services/authorization/src/types.rs
Labels: approved, lgtm, size/L

#339 chore(network): upgrade tentacle to v0.3.0alpha5
  core/network/Cargo.toml
  core/network/src/connection/control.rs
  core/network/src/connection/keeper.rs
  core/network/src/connection/mod.rs
  core/network/src/error.rs
  core/network/src/event.rs
  core/network/src/peer_manager/mod.rs
  core/network/src/peer_manager/save_restore.rs
Labels: approved, lgtm, size/L

#342 chore: Add lint pipeline
  charts/rust/.helmignore
  charts/rust/Chart.yaml
  charts/rust/Makefile
  charts/rust/README.md
  charts/rust/templates/NOTES.txt
  charts/rust/templates/_helpers.tpl
  charts/rust/templates/canary.yaml
  charts/rust/templates/deployment.yaml
  charts/rust/templates/hpa.yaml
  charts/rust/templates/ingress.yaml
  charts/rust/templates/ksvc.yaml
  charts/rust/templates/service.yaml
  charts/rust/values.yaml
  jenkins-x-e2e.yml
  jenkins-x-fmt.yml
  jenkins-x-lint.yml
  jenkins-x-unit.yml
  jenkins-x.yml
Labels: approved, size/XL

#340 refactor(tests): trust metric integration tests
  Cargo.toml
  Makefile
  core/network/src/lib.rs
  core/network/src/peer_manager/diagnostic.rs
  core/network/src/peer_manager/mod.rs
  core/network/src/service.rs
  protocol/src/traits/network.rs
  tests/trust_metric_all/common.rs
  tests/trust_metric_all/consensus.rs
  tests/trust_metric_all/mempool.rs
  tests/trust_metric_all/mod.rs
  tests/trust_metric_all/node.rs
  tests/trust_metric_all/node/client_node.rs
  tests/trust_metric_all/node/diagnostic.rs
  tests/trust_metric_all/node/full_node.rs
  tests/trust_metric_all/node/full_node/builder.rs
  tests/trust_metric_all/node/full_node/default_start.rs
  tests/trust_metric_all/node/sync.rs
Labels: approved, lgtm, size/XXL

#343 test(consensus): add unit test of current consensus status
  core/consensus/Cargo.toml
  core/consensus/src/status.rs
  core/consensus/src/tests/mod.rs
  core/consensus/src/tests/status.rs
  core/consensus/src/tests/synchronization.rs
Labels: approved, lgtm, size/L

#347 feat!: add 'name' field in event struct
  built-in-services/asset/src/lib.rs
  core/api/src/schema/receipt.rs
  framework/src/binding/tests/sdk.rs
  framework/src/executor/tests/service_call_service.rs
  framework/src/executor/tests/test_service.rs
  jenkins-x-unit.yml
  protocol/src/codec/receipt.rs
  protocol/src/fixed_codec/tests/mod.rs
  protocol/src/types/primitive.rs
  protocol/src/types/receipt.rs
  protocol/src/types/service_context.rs
Labels: approved, lgtm, size/M

#315 feat(api)!: Allowed to return None
  .gitignore
  core/api/src/adapter/mod.rs
  core/api/src/lib.rs
  protocol/src/traits/api.rs
  tests/e2e/docker-compose-e2e-test.yaml
  tests/e2e/multisig.ts
  tests/e2e/package.json
  tests/e2e/sdk.test.ts
  tests/e2e/tsconfig.json
  tests/e2e/utils.ts
  tests/e2e/yarn.lock
Labels: approved, lgtm, size/L

#341 build: Release CHANGELOG v0.2.0-alpha.0
  CHANGELOG/CHANGELOG-0.2.md
Labels: approved, size/S

#353 ci: Add semantic config
  .github/semantic.yml
Labels: approved, lgtm, size/S

#352 test(e2e): add more cases of multi-signature service
  core/mempool/src/adapter/mod.rs
  core/mempool/src/lib.rs
  core/mempool/src/tests/mod.rs
  tests/e2e/jest.config.js
  tests/e2e/multisig.ts
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/sdk.test.ts
  tests/e2e/tsconfig.json
  tests/e2e/utils.ts
  tests/e2e/yarn.lock
Labels: approved, lgtm, size/XXL

#355 feat(framework)!: Add return type ServiceResponse<String> for tx_hook
  binding-macro/src/service.rs
  binding-macro/tests/mod.rs
  framework/src/executor/tests/test_service.rs
  protocol/src/traits/binding.rs
Labels: approved, lgtm, size/L

#356 feat(framework)!: add return type for tx_hook and change tx and tx hook run logic
  framework/src/executor/error.rs
  framework/src/executor/mod.rs
  framework/src/executor/tests/mod.rs
  framework/src/executor/tests/test_service.rs
  src/default_start.rs
Labels: approved, lgtm, size/L

#349 ci: Add chaos test pipeline
  charts/deploy-chaos/.helmignore
  charts/deploy-chaos/Chart.yaml
  charts/deploy-chaos/templates/_helpers.tpl
  charts/deploy-chaos/templates/muta-chaos-crd.yaml
  charts/deploy-chaos/values.yaml
  devtools/kube/deploy-chaos-crd-template.yml
  jenkins-x-chaos.yml
  jenkins-x.yml
Labels: approved, lgtm, size/L

#354 refactor(consensus)!: replace Validator address bytes with pubkey bytes
  Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/metadata/src/tests/mod.rs
  core/api/src/schema/block.rs
  core/consensus/Cargo.toml
  core/consensus/src/adapter.rs
  core/consensus/src/consensus.rs
  core/consensus/src/engine.rs
  core/consensus/src/status.rs
  core/consensus/src/synchronization.rs
  core/consensus/src/tests/status.rs
  core/consensus/src/tests/synchronization.rs
  core/consensus/src/util.rs
  devtools/chain/config.toml
  devtools/chain/genesis.toml
  devtools/keypair/Cargo.toml
  devtools/keypair/src/main.rs
  examples/config-1.toml
  examples/config-2.toml
  examples/config-3.toml
  examples/config-4.toml
  examples/genesis.toml
  framework/src/binding/tests/sdk.rs
  protocol/Cargo.toml
  protocol/src/codec/block.rs
  protocol/src/fixed_codec/tests/mod.rs
  protocol/src/traits/consensus.rs
  protocol/src/types/block.rs
  protocol/src/types/primitive.rs
  src/default_start.rs
  tests/e2e/package.json
  tests/e2e/sdk.test.ts
  tests/e2e/yarn.lock
  tests/trust_metric_all/node/full_node/default_start.rs
Labels: approved, lgtm, size/XL

#361 Revert "refactor(consensus)!: replace Validator address bytes with pubkey bytes"
  Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/metadata/src/tests/mod.rs
  core/api/src/schema/block.rs
  core/consensus/Cargo.toml
  core/consensus/src/adapter.rs
  core/consensus/src/consensus.rs
  core/consensus/src/engine.rs
  core/consensus/src/status.rs
  core/consensus/src/synchronization.rs
  core/consensus/src/tests/status.rs
  core/consensus/src/tests/synchronization.rs
  core/consensus/src/util.rs
  devtools/chain/config.toml
  devtools/chain/genesis.toml
  devtools/keypair/Cargo.toml
  devtools/keypair/src/main.rs
  examples/config-1.toml
  examples/config-2.toml
  examples/config-3.toml
  examples/config-4.toml
  examples/genesis.toml
  framework/src/binding/tests/sdk.rs
  protocol/Cargo.toml
  protocol/src/codec/block.rs
  protocol/src/fixed_codec/tests/mod.rs
  protocol/src/traits/consensus.rs
  protocol/src/types/block.rs
  protocol/src/types/primitive.rs
  src/default_start.rs
  tests/e2e/package.json
  tests/e2e/sdk.test.ts
  tests/e2e/yarn.lock
  tests/trust_metric_all/node/full_node/default_start.rs
Labels: size/XL

#362 ci: Fix chaos test
  charts/deploy-chaos/values.yaml
  jenkins-x-chaos.yml
Labels: approved, lgtm, size/S

#359 perf(mempool): parallel verifying signatures in mempool
  core/mempool/src/adapter/mod.rs
Labels: approved, lgtm, size/L

#367 fix(executor): The logic to deal with tx_hook and tx_body
  framework/src/executor/mod.rs
  framework/src/executor/tests/framework.rs
  framework/src/executor/tests/framework_genesis_services.toml
  framework/src/executor/tests/mod.rs
Labels: approved, lgtm, size/L

#368 feat: update overlord version
  core/consensus/Cargo.toml
Labels: approved, lgtm, size/XS

#369 refactor: increacing `cycles_limit` to avoid errors in the example
  built-in-services/asset/src/lib.rs
  built-in-services/authorization/src/lib.rs
  built-in-services/metadata/src/lib.rs
  built-in-services/multi-signature/src/lib.rs
  built-in-services/util/src/lib.rs
  devtools/chain/genesis.toml
  framework/src/executor/tests/framework.rs
  framework/src/executor/tests/test_service.rs
Labels: approved, lgtm, size/M

#370 ci: Disabled auto tag version
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#365 perf(executor): use inner call instead of service dispatcher
  Cargo.toml
  benchmark/bench.rs
  benchmark/benchmark_genesis.toml
  benchmark/governance/mod.rs
  benchmark/governance/types.rs
  benchmark/mod.rs
  binding-macro/tests/mod.rs
  built-in-services/asset/src/lib.rs
  built-in-services/asset/src/tests/mod.rs
  built-in-services/authorization/Cargo.toml
  built-in-services/authorization/src/lib.rs
  built-in-services/authorization/src/types.rs
  built-in-services/metadata/src/tests/mod.rs
  built-in-services/multi-signature/src/lib.rs
  built-in-services/multi-signature/src/tests/mod.rs
  built-in-services/util/src/tests/mod.rs
  core/mempool/src/adapter/mod.rs
  examples/muta-chain.rs
  framework/src/binding/sdk/mod.rs
  framework/src/binding/tests/sdk.rs
  framework/src/executor/mod.rs
  framework/src/executor/tests/framework.rs
  framework/src/executor/tests/mod.rs
  framework/src/executor/tests/service_call_service.rs
  framework/src/executor/tests/test_service.rs
  protocol/src/traits/binding.rs
  protocol/src/traits/executor.rs
  protocol/src/traits/mod.rs
  src/default_start.rs
  tests/trust_metric_all/node/full_node.rs
Labels: approved, lgtm, size/XXL

#373 fix(storage): panic when test batch receipts get
  core/storage/src/tests/adapter.rs
  core/storage/src/tests/mod.rs
  core/storage/src/tests/storage.rs
Labels: approved, lgtm, size/L

#371 fix(consensus): return an error when committing an outdated block
  core/consensus/Cargo.toml
  core/consensus/src/engine.rs
  core/consensus/src/lib.rs
  core/consensus/src/tests/engine.rs
  core/consensus/src/tests/mod.rs
  core/consensus/src/tests/status.rs
Labels: approved, lgtm, size/XL

#372 fix(network): remove unsafe conversion between Connectedness and usize
  core/network/src/peer_manager/peer.rs
Labels: approved, lgtm, size/M

#366 ci: fix chaos benchmark
  CHANGELOG/CHANGELOG-0.3.md
  charts/deploy-chaos/templates/muta-chaos-crd.yaml
  charts/deploy-chaos/values.yaml
  jenkins-x-chaos.yml
  jenkins-x.yml
Labels: size/XL

#376 feat: Add global panic hook
  Cargo.toml
  common/logger/Cargo.toml
  common/logger/src/lib.rs
  src/default_start.rs
Labels: approved, lgtm, size/M

#379 fix(mempool): Ensure that there are no duplicate transactions in the order transaction
  core/mempool/src/lib.rs
  core/mempool/src/tests/mempool.rs
  core/mempool/src/tests/mod.rs
Labels: approved, lgtm, size/M

#374 feat(protocol)!: bech32 encoded address
  benchmark/benchmark_genesis.toml
  benchmark/mod.rs
  built-in-services/asset/src/lib.rs
  built-in-services/asset/src/tests/mod.rs
  built-in-services/metadata/src/tests/mod.rs
  built-in-services/multi-signature/src/lib.rs
  built-in-services/multi-signature/src/tests/curd_test.rs
  built-in-services/multi-signature/src/tests/recursion_test.rs
  built-in-services/util/src/tests/mod.rs
  charts/deploy-chaos/values.yaml
  common/crypto/Cargo.toml
  common/crypto/src/lib.rs
  core/api/src/lib.rs
  core/api/src/schema/mod.rs
  core/api/src/schema/transaction.rs
  core/consensus/src/adapter.rs
  core/consensus/src/fixed_types.rs
  core/consensus/src/tests/synchronization.rs
  core/mempool/src/adapter/mod.rs
  core/mempool/src/tx_cache.rs
  core/storage/examples/bench.rs
  core/storage/src/tests/mod.rs
  devtools/chain/README.md
  devtools/chain/config.toml
  devtools/chain/genesis.toml
  devtools/keypair/Cargo.toml
  devtools/keypair/src/main.rs
  devtools/kube/deploy-chaos-crd-template.yml
  examples/config-1.toml
  examples/config-2.toml
  examples/config-3.toml
  examples/config-4.toml
  examples/genesis.toml
  framework/src/executor/tests/framework.rs
  framework/src/executor/tests/genesis_services.toml
  framework/src/executor/tests/mod.rs
  protocol/Cargo.toml
  protocol/build.rs
  protocol/src/types/mod.rs
  protocol/src/types/primitive.rs
  src/default_start.rs
  tests/e2e/package.json
  tests/e2e/sdk.test.ts
  tests/e2e/yarn.lock
  tests/trust_metric_all/node/client_node.rs
  tests/trust_metric_all/node/full_node/default_start.rs
Labels: approved, lgtm, size/XL

#382 feat: add from_hex() back into Address
  protocol/src/types/primitive.rs
Labels: approved, lgtm, size/S

#381 refactor(service): add interface for service
  benchmark/governance/mod.rs
  built-in-services/asset/src/lib.rs
  built-in-services/metadata/src/lib.rs
  built-in-services/multi-signature/src/lib.rs
  built-in-services/multi-signature/src/tests/curd_test.rs
Labels: approved, lgtm, size/L
