Repository nervosnetwork/muta, pull requests merged in 2020-09, with the labels that each got.

#433 feat: add byzantine test script
  .gitignore
  Makefile
  byzantine/Cargo.toml
  byzantine/README.md
  byzantine/generators.toml
  byzantine/tests/byz.test.ts
  byzantine/tests/jest.config.js
  byzantine/tests/package.json
  byzantine/tests/yarn.lock
  core/consensus/src/tests/engine.rs
  core/consensus/src/wal.rs
  examples/config-1.toml
  examples/config-2.toml
  examples/config-3.toml
  examples/config-4.toml
  jenkins-x-unit.yml
Labels: approved, lgtm, size/XXL

#435 feat(logger): split log file by size
  common/logger/Cargo.toml
  common/logger/src/date_fixed_roller.rs
  common/logger/src/lib.rs
  devtools/chain/config.toml
  src/config.rs
  src/lib.rs
  tests/trust_metric_all/logger.rs
Labels: approved, lgtm, size/L

#431 feat(network): ping metric from gauge vec to histogram vec
  common/apm/src/metrics.rs
  common/apm/src/metrics/network.rs
  core/network/src/protocols/ping/behaviour.rs
Labels: approved, lgtm, size/S

#437 refactor: change the overlord gap into configurable
  core/consensus/src/adapter.rs
  core/consensus/src/lib.rs
  devtools/chain/config.toml
  src/config.rs
  src/default_start.rs
  tests/common/node/config.rs
  tests/common/node/full_node/default_start.rs
Labels: approved, lgtm, size/M

#434 feat(logger): add structured log api
  common/logger/Cargo.toml
  common/logger/log.yml
  common/logger/src/lib.rs
Labels: approved, lgtm, size/M

#440 fix: fix framework to deal with state while tx runs fail
  framework/src/executor/mod.rs
Labels: approved, lgtm, size/XS

#439 fix(network): identify protocol: possible dead lock in identification
  core/network/src/protocols/identify/identification.rs
Labels: approved, lgtm, size/S

#441 feat(protocol): network MessageCodec to sync
  byzantine/src/invalid_types.rs
  core/consensus/src/fixed_types.rs
  core/mempool/src/adapter/mod.rs
  core/network/src/outbound/gossip.rs
  core/network/src/outbound/rpc.rs
  core/network/src/reactor/mod.rs
  protocol/src/traits/network.rs
Labels: approved, lgtm, size/M

#442 fix: update example configs, fix send transaction in byzantine
  byzantine/README.md
  byzantine/generators.toml
  byzantine/src/behaviors.rs
  byzantine/src/commander.rs
  byzantine/src/invalid_types.rs
  byzantine/src/utils.rs
  byzantine/src/worker.rs
  examples/config-1.toml
  examples/config-2.toml
  examples/config-3.toml
  examples/config-4.toml
Labels: approved, lgtm, size/L

#443 build!: Release muta v0.2.0-rc.2
  Cargo.toml
  binding-macro/Cargo.toml
  built-in-services/asset/Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/multi-signature/Cargo.toml
  built-in-services/util/Cargo.toml
  common/channel/Cargo.toml
  common/config-parser/Cargo.toml
  common/crypto/Cargo.toml
  common/logger/Cargo.toml
  common/merkle/Cargo.toml
  common/pubsub/Cargo.toml
  core/api/Cargo.toml
  core/consensus/Cargo.toml
  core/mempool/Cargo.toml
  core/network/Cargo.toml
  core/storage/Cargo.toml
  devtools/keypair/Cargo.toml
  framework/Cargo.toml
  protocol/Cargo.toml
Labels: approved, lgtm, size/M

#444 build: revert rayon to version 1.3
  common/merkle/Cargo.toml
  framework/Cargo.toml
Labels: approved, lgtm, size/XS

#445 build: build muta v0.2.0-rc.2.1
  Cargo.toml
  binding-macro/Cargo.toml
  built-in-services/asset/Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/multi-signature/Cargo.toml
  built-in-services/util/Cargo.toml
  common/channel/Cargo.toml
  common/config-parser/Cargo.toml
  common/crypto/Cargo.toml
  common/logger/Cargo.toml
  common/merkle/Cargo.toml
  common/pubsub/Cargo.toml
  core/api/Cargo.toml
  core/consensus/Cargo.toml
  core/mempool/Cargo.toml
  core/network/Cargo.toml
  core/storage/Cargo.toml
  devtools/keypair/Cargo.toml
  framework/Cargo.toml
  protocol/Cargo.toml
Labels: size/M

#447 refactor(consensus): view change reason adapts to structure log
  core/consensus/Cargo.toml
  core/consensus/src/engine.rs
Labels: approved, lgtm, size/S

#448 fix(state): If value is an empty byte it needs to return none
  framework/src/binding/state/mod.rs
Labels: approved, lgtm, size/M

#449 feat(metric): add accumulated network message size count
  common/apm/src/metrics/network.rs
  core/network/src/outbound/gossip.rs
  core/network/src/outbound/rpc.rs
  core/network/src/protocols/transmitter/behaviour.rs
  core/network/src/protocols/transmitter/message.rs
  core/network/src/reactor/router.rs
  core/network/src/traits.rs
Labels: approved, lgtm, size/M

#438 refactor(consensus): upgrade overlord version to v0.2.0
  byzantine/Cargo.toml
  core/consensus/Cargo.toml
  core/consensus/src/consensus.rs
  src/default_start.rs
  tests/common/node/full_node/default_start.rs
Labels: approved, lgtm, size/S

#450 fix(logger): add structured api
  common/logger/README.md
  common/logger/src/lib.rs
Labels: approved, lgtm, size/S

#446 feat(api): dump profile data through http request
  core/api/Cargo.toml
  core/api/src/config.rs
  core/api/src/lib.rs
  devtools/chain/config.toml
  src/config.rs
  src/default_start.rs
Labels: approved, lgtm, size/L

#452 fix(metric): network broadcast all data size
  core/network/src/peer_manager/shared.rs
  core/network/src/protocols/transmitter/behaviour.rs
  core/network/src/traits.rs
Labels: approved, lgtm, size/S

#451 fix(network): wrong connected consensus peer count
  core/network/src/peer_manager/mod.rs
  core/network/src/peer_manager/test_manager.rs
Labels: approved, lgtm, size/M

#454 refactor: return Ok(None) when get none
  framework/src/binding/store/array.rs
  framework/src/binding/store/map.rs
Labels: approved, lgtm, size/S

#455 feat(logger): add a json macro to generate json object
  common/logger/Cargo.toml
  common/logger/README.md
  common/logger/src/lib.rs
  core/consensus/src/engine.rs
Labels: approved, lgtm, size/M

#456 fix(cli): expose version, author and app_name to be customized
  core/cli/src/lib.rs
  core/cli/src/tests/mod.rs
  examples/muta-chain.rs
  src/lib.rs
Labels: approved, lgtm, size/L

#457 build: Release v0.2.0
  CHANGELOG/CHANGELOG-0.2.md
  Cargo.toml
  binding-macro/Cargo.toml
  built-in-services/asset/Cargo.toml
  built-in-services/authorization/Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/multi-signature/Cargo.toml
  built-in-services/util/Cargo.toml
  byzantine/Cargo.toml
  common/apm/Cargo.toml
  common/channel/Cargo.toml
  common/config-parser/Cargo.toml
  common/crypto/Cargo.toml
  common/logger/Cargo.toml
  common/merkle/Cargo.toml
  common/pubsub/Cargo.toml
  core/api/Cargo.toml
  core/cli/Cargo.toml
  core/consensus/Cargo.toml
  core/mempool/Cargo.toml
  core/network/Cargo.toml
  core/run/Cargo.toml
  core/storage/Cargo.toml
  devtools/keypair/Cargo.toml
  examples/muta-chain.rs
  framework/Cargo.toml
  protocol/Cargo.toml
Labels: approved, lgtm, size/XL

#458 perf: remove unnecessary clone
  Makefile
  built-in-services/asset/src/tests/mod.rs
  built-in-services/authorization/src/lib.rs
  built-in-services/metadata/src/tests/mod.rs
  built-in-services/multi-signature/src/lib.rs
  built-in-services/multi-signature/src/tests/mod.rs
  built-in-services/multi-signature/src/types.rs
  built-in-services/util/src/tests/mod.rs
  common/apm/src/metrics/storage.rs
  core/api/src/adapter/mod.rs
  core/consensus/src/adapter.rs
  core/consensus/src/engine.rs
  core/consensus/src/message.rs
  core/consensus/src/synchronization.rs
  core/consensus/src/tests/engine.rs
  core/consensus/src/tests/synchronization.rs
  core/mempool/src/adapter/message.rs
  core/mempool/src/adapter/mod.rs
  core/mempool/src/lib.rs
  core/mempool/src/tests/mempool.rs
  core/mempool/src/tests/mod.rs
  core/mempool/src/tx_cache.rs
  core/network/examples/buycopy.rs
  core/network/src/outbound/rpc.rs
  core/network/src/reactor/router.rs
  core/run/src/lib.rs
  core/storage/Cargo.toml
  core/storage/examples/bench.rs
  core/storage/src/adapter/rocks.rs
  core/storage/src/lib.rs
  core/storage/src/tests/storage.rs
  devtools/keypair/src/main.rs
  framework/src/binding/sdk/chain_querier.rs
  framework/src/binding/tests/sdk.rs
  framework/src/executor/tests/framework.rs
  framework/src/executor/tests/mod.rs
  protocol/Cargo.toml
  protocol/src/traits/api.rs
  protocol/src/traits/consensus.rs
  protocol/src/traits/mempool.rs
  protocol/src/traits/storage.rs
  protocol/src/types/primitive.rs
  tests/common/node/full_node/default_start.rs
Labels: approved, lgtm, size/XL

#459 feat(consensus): metric proposal ordered tx len and sync tx len
  common/apm/src/metrics/consensus.rs
  core/consensus/src/engine.rs
Labels: approved, lgtm, size/S

#462 fix: smol_str compilation failed
  benchmark/bench_executor.rs
  benchmark/mod.rs
  binding-macro/src/service.rs
  core/api/src/adapter/mod.rs
  core/consensus/src/adapter.rs
  core/consensus/src/wal.rs
  core/network/src/common.rs
  core/network/src/endpoint.rs
  core/network/src/peer_manager/session_book.rs
  core/network/src/peer_manager/test_manager.rs
  core/network/src/protocols/discovery/addr.rs
  core/network/src/protocols/identify/protocol.rs
  core/network/src/protocols/ping/protocol.rs
  core/network/src/protocols/transmitter/behaviour.rs
  core/run/src/lib.rs
  core/storage/src/lib.rs
  framework/src/binding/state/trie_db.rs
  framework/src/binding/store/array.rs
  rust-toolchain
  tests/common/node/full_node/default_start.rs
  tests/trust_metric_all/mempool.rs
Labels: approved, lgtm, size/M

#460 fix(network): connecting hang
  core/network/Cargo.toml
  core/network/src/peer_manager/mod.rs
  core/network/src/peer_manager/test_manager.rs
  core/network/src/protocols/identify.rs
  core/network/src/protocols/identify/protocol.rs
Labels: approved, lgtm, size/L

#463 feat(cli): add config for default config and genesis path
  core/cli/src/lib.rs
  core/cli/src/tests/mod.rs
  examples/muta-chain.rs
  src/lib.rs
Labels: approved, lgtm, size/L

#464 build: bump version to v0.2.1
  Cargo.toml
  binding-macro/Cargo.toml
  built-in-services/asset/Cargo.toml
  built-in-services/authorization/Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/multi-signature/Cargo.toml
  built-in-services/util/Cargo.toml
  byzantine/Cargo.toml
  common/apm/Cargo.toml
  common/channel/Cargo.toml
  common/config-parser/Cargo.toml
  common/crypto/Cargo.toml
  common/logger/Cargo.toml
  common/merkle/Cargo.toml
  common/pubsub/Cargo.toml
  core/api/Cargo.toml
  core/cli/Cargo.toml
  core/consensus/Cargo.toml
  core/mempool/Cargo.toml
  core/network/Cargo.toml
  core/run/Cargo.toml
  core/storage/Cargo.toml
  devtools/keypair/Cargo.toml
  examples/muta-chain.rs
  framework/Cargo.toml
  protocol/Cargo.toml
Labels: approved, lgtm, size/M
