Repository nervosnetwork/muta, pull requests merged in 2020-08, with the labels that each got.

#383 docs: fix gql_api.sh and update graphql_api.md
  devtools/chain/genesis.toml
  docs/build/gql_api.sh
  docs/graphql_api.md
Labels: approved, lgtm, size/L

#386 build: Release v0.2.0-beta1
  CHANGELOG/CHANGELOG-0.1.md
  CHANGELOG/CHANGELOG-0.2.md
  CHANGELOG/CHANGELOG-0.3.md
Labels: size/XXL

#389 docs: Fix links in README.md
  README.md
  README_CN.md
Labels: approved, lgtm, size/XS

#377 fix(consensus): Add timestamp checking
  core/consensus/src/engine.rs
  core/consensus/src/lib.rs
  core/consensus/src/util.rs
Labels: approved, lgtm, size/M

#387 docs: available resources for muta
  README.md
  README_CN.md
  docs/resources.md
Labels: approved, lgtm, size/S

#394 feat(mempool): remove peer trust report on timeout tx
  core/mempool/src/adapter/mod.rs
  tests/trust_metric_all/common.rs
  tests/trust_metric_all/mempool.rs
Labels: approved, lgtm, size/M

#391 feat(benchmark): add a perf benchmark macro
  benchmark/bench.rs
  benchmark/mod.rs
Labels: approved, lgtm, size/M

#396 feat(protocol)!: use bech32 address hrp from genesis block
  built-in-services/metadata/src/tests/mod.rs
  core/consensus/src/adapter.rs
  core/consensus/src/tests/engine.rs
  core/consensus/src/tests/status.rs
  core/consensus/src/tests/synchronization.rs
  core/mempool/src/adapter/mod.rs
  devtools/chain/genesis.toml
  examples/genesis.toml
  protocol/Cargo.toml
  protocol/build.rs
  protocol/src/lib.rs
  protocol/src/types/mod.rs
  protocol/src/types/primitive.rs
  src/default_start.rs
  tests/trust_metric_all/node/full_node/default_start.rs
Labels: approved, lgtm, size/L

#395 build(framework): Update rocksdb to v0.14
  framework/Cargo.toml
  framework/src/binding/state/trie_db.rs
Labels: approved, lgtm, size/XS

#385 feat(Cargo): add random leader feature for muta
  Cargo.toml
Labels: approved, lgtm, size/XS

#397 perf(metrics): Add metrics of state
  common/apm/src/metrics/storage.rs
  framework/src/binding/state/trie_db.rs
Labels: approved, lgtm, size/M

#398 build: Release v0.2.0-beta.2
  CHANGELOG/CHANGELOG-0.2.md
  CHANGELOG/README.md
Labels: approved, lgtm, size/S

#399 ci: Fix release jx
  jenkins-x.yml
Labels: size/L

#388 feat(network): limit connections from same ip
  core/network/src/common.rs
  core/network/src/config.rs
  core/network/src/connection/control.rs
  core/network/src/connection/mod.rs
  core/network/src/metrics.rs
  core/network/src/peer_manager/mod.rs
  core/network/src/peer_manager/session_book.rs
  core/network/src/peer_manager/shared.rs
  core/network/src/peer_manager/test_manager.rs
  core/network/src/reactor/router.rs
  core/network/src/selfcheck.rs
  core/network/src/test/mock.rs
  core/network/src/traits.rs
  src/config.rs
  src/default_start.rs
Labels: approved, lgtm, size/XL

#393 feat(network): limit inbound and outbound connections
  core/network/src/config.rs
  core/network/src/error.rs
  core/network/src/peer_manager/mod.rs
  core/network/src/peer_manager/session_book.rs
  core/network/src/peer_manager/test_manager.rs
  src/config.rs
  src/default_start.rs
  tests/trust_metric_all/node/full_node/default_start.rs
Labels: approved, lgtm, size/XL

#401 build: Update github Pull-Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/S

#390 feat(sync): Limit the maximum height of once sync
  common/apm/src/metrics/consensus.rs
  core/consensus/src/synchronization.rs
Labels: approved, lgtm, size/M

#400 fix(apm): Return the correct time
  common/apm/src/lib.rs
  common/apm/src/metrics.rs
Labels: approved, lgtm, size/S

#403 build: Release v0.2.0-beta3
  CHANGELOG/CHANGELOG-0.2.md
  CHANGELOG/README.md
  Cargo.toml
  binding-macro/Cargo.toml
  built-in-services/asset/Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/multi-signature/Cargo.toml
  built-in-services/util/Cargo.toml
  common/channel/Cargo.toml
  common/config-parser/Cargo.toml
  common/crypto/Cargo.toml
  common/logger/Cargo.toml
  common/merkle/Cargo.toml
  common/pubsub/Cargo.toml
  core/api/Cargo.toml
  core/consensus/Cargo.toml
  core/mempool/Cargo.toml
  core/network/Cargo.toml
  core/storage/Cargo.toml
  devtools/keypair/Cargo.toml
  framework/Cargo.toml
  protocol/Cargo.toml
Labels: size/M

#405 fix: load hrp before deserializing genesis payload to take hrp effect
  protocol/src/types/primitive.rs
  src/default_start.rs
Labels: approved, lgtm, size/M

#404 perf(state): add state cache for trieDB
  benchmark/mod.rs
  devtools/chain/config.toml
  examples/config-1.toml
  examples/config-2.toml
  examples/config-3.toml
  examples/config-4.toml
  framework/Cargo.toml
  framework/src/binding/state/trie_db.rs
  framework/src/binding/tests/state.rs
  src/config.rs
  src/default_start.rs
Labels: approved, lgtm, size/L

#402 feat(api): Support enabled TLS
  core/api/Cargo.toml
  core/api/src/config.rs
  core/api/src/lib.rs
  devtools/chain/config.toml
  src/config.rs
  src/default_start.rs
Labels: approved, lgtm, size/M

#408 fix!: service field of event is not binded to ctx.service
  built-in-services/asset/src/lib.rs
  built-in-services/authorization/src/lib.rs
  built-in-services/metadata/src/lib.rs
  built-in-services/multi-signature/src/lib.rs
  built-in-services/util/src/lib.rs
  examples/muta-chain.rs
  framework/src/executor/tests/framework.rs
  framework/src/executor/tests/mod.rs
  framework/src/executor/tests/test_service.rs
  protocol/src/types/service_context.rs
Labels: approved, lgtm, size/M

#407 build: Release v0.2.0-beta.4
  CHANGELOG/CHANGELOG-0.2.md
  Cargo.toml
  binding-macro/Cargo.toml
  built-in-services/asset/Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/multi-signature/Cargo.toml
  built-in-services/util/Cargo.toml
  common/channel/Cargo.toml
  common/config-parser/Cargo.toml
  common/crypto/Cargo.toml
  common/logger/Cargo.toml
  common/merkle/Cargo.toml
  common/pubsub/Cargo.toml
  core/api/Cargo.toml
  core/consensus/Cargo.toml
  core/mempool/Cargo.toml
  core/network/Cargo.toml
  core/storage/Cargo.toml
  devtools/keypair/Cargo.toml
  framework/Cargo.toml
  protocol/Cargo.toml
Labels: approved, lgtm, size/M

#380 feat(network): split transmitter data
  core/network/Cargo.toml
  core/network/src/connection/control.rs
  core/network/src/connection/mod.rs
  core/network/src/error.rs
  core/network/src/message/mod.rs
  core/network/src/outbound/gossip.rs
  core/network/src/outbound/rpc.rs
  core/network/src/protocols/core.rs
  core/network/src/protocols/mod.rs
  core/network/src/protocols/transmitter.rs
  core/network/src/protocols/transmitter/behaviour.rs
  core/network/src/protocols/transmitter/message.rs
  core/network/src/protocols/transmitter/protocol.rs
  core/network/src/reactor/router.rs
  core/network/src/service.rs
  core/network/src/traits.rs
  protocol/src/traits/network.rs
Labels: approved, lgtm, size/XXL

#406 feat(network): verify chain id during protocol handshake
  Cargo.toml
  core/network/src/connection/keeper.rs
  core/network/src/event.rs
  core/network/src/peer_manager/mod.rs
  core/network/src/peer_manager/test_manager.rs
  core/network/src/protocols/core.rs
  core/network/src/protocols/discovery.rs
  core/network/src/protocols/discovery/behaviour.rs
  core/network/src/protocols/discovery/protocol.rs
  core/network/src/protocols/identify.rs
  core/network/src/protocols/identify/behaviour.rs
  core/network/src/protocols/identify/identification.rs
  core/network/src/protocols/identify/message.rs
  core/network/src/protocols/identify/protocol.rs
  core/network/src/protocols/identify/tests.rs
  core/network/src/protocols/mod.rs
  core/network/src/protocols/ping/protocol.rs
  core/network/src/protocols/transmitter.rs
  core/network/src/protocols/transmitter/protocol.rs
  core/network/src/service.rs
  core/network/src/test/mock.rs
  src/default_start.rs
  tests/common/mod.rs
  tests/common/node.rs
  tests/common/node/config.rs
  tests/common/node/consts.rs
  tests/common/node/diagnostic.rs
  tests/common/node/full_node.rs
  tests/common/node/full_node/builder.rs
  tests/common/node/full_node/default_start.rs
  tests/common/node/full_node/error.rs
  tests/common/node/full_node/memory_db.rs
  tests/common/node/sync.rs
  tests/trust_metric.rs
  tests/trust_metric_all/client_node.rs
  tests/trust_metric_all/common.rs
  tests/trust_metric_all/consensus.rs
  tests/trust_metric_all/mempool.rs
  tests/trust_metric_all/mod.rs
  tests/verify_chain_id.rs
Labels: approved, lgtm, size/XXL

#392 refactor(service): change service interface return type
  benchmark/governance/mod.rs
  built-in-services/asset/src/lib.rs
  built-in-services/metadata/src/lib.rs
  built-in-services/multi-signature/src/lib.rs
  protocol/src/traits/binding.rs
Labels: approved, lgtm, size/L

#413 build: Release v0.2.0-rc
  CHANGELOG/CHANGELOG-0.2.md
  Cargo.toml
  binding-macro/Cargo.toml
  built-in-services/asset/Cargo.toml
  built-in-services/metadata/Cargo.toml
  built-in-services/multi-signature/Cargo.toml
  built-in-services/util/Cargo.toml
  common/channel/Cargo.toml
  common/config-parser/Cargo.toml
  common/crypto/Cargo.toml
  common/logger/Cargo.toml
  common/merkle/Cargo.toml
  common/pubsub/Cargo.toml
  core/api/Cargo.toml
  core/consensus/Cargo.toml
  core/mempool/Cargo.toml
  core/network/Cargo.toml
  core/storage/Cargo.toml
  devtools/keypair/Cargo.toml
  framework/Cargo.toml
  protocol/Cargo.toml
Labels: size/M

#411 refactor(service): change the rlp decode list
  built-in-services/multi-signature/src/lib.rs
  built-in-services/multi-signature/src/tests/curd_test.rs
Labels: approved, lgtm, size/L

#378 ci: fix chaos test
  charts/deploy-chaos/templates/muta-benchmark.yaml
  charts/deploy-chaos/templates/muta-chaos-crd.yaml
  charts/deploy-chaos/values.yaml
  jenkins-x-chaos.yml
Labels: size/M

#416 feat(network): add more metrics
  common/apm/src/metrics/network.rs
  core/network/src/peer_manager/mod.rs
  core/network/src/protocols/ping/behaviour.rs
  core/network/src/protocols/ping/protocol.rs
  core/network/src/protocols/transmitter/protocol.rs
  core/network/src/reactor/mod.rs
Labels: approved, lgtm, size/L

#417 feat(network): add tentacle_metrics feature
  Cargo.toml
  core/network/Cargo.toml
Labels: approved, lgtm, size/XS

#410 refactor(benchmark): refactor benchmark macros
  benchmark/bench_executor.rs
  benchmark/bench_mempool.rs
  benchmark/benchmark_genesis.toml
  benchmark/mod.rs
Labels: approved, lgtm, size/L

#419 ci: Add concurrencyPolicy for benchmark
  charts/deploy-chaos/templates/muta-benchmark.yaml
Labels: size/XS

#418 fix(network): give up peer because of handshake timeout
  core/network/src/connection/keeper.rs
  core/network/src/event.rs
  core/network/src/peer_manager/mod.rs
Labels: approved, lgtm, size/S

#421 refactor: update to latest overlord
  core/consensus/Cargo.toml
Labels: approved, lgtm, size/XS

#420 refactor(consensus): change an error log info when get block
  core/consensus/src/engine.rs
Labels: approved, lgtm, size/XS

#423 fix(network): give up a peer without log a reason
  core/network/src/peer_manager/mod.rs
Labels: approved, lgtm, size/XS

#424 fix(network): double decrease connecting gauge
  core/network/src/peer_manager/mod.rs
Labels: approved, lgtm, size/XS

#414 fix(consensus): recover and insert tx to mempool to avoid inactivation
  Cargo.toml
  core/consensus/Cargo.toml
  core/consensus/src/engine.rs
  core/consensus/src/lib.rs
  core/consensus/src/wal.rs
  core/mempool/src/lib.rs
  core/mempool/src/tests/mempool.rs
  core/mempool/src/tests/mod.rs
  protocol/Cargo.toml
  src/default_start.rs
  tests/common/node/full_node/default_start.rs
Labels: approved, lgtm, size/L

#422 test: fix e2e-test
  tests/e2e/multisig.ts
  tests/e2e/package.json
  tests/e2e/sdk.test.ts
  tests/e2e/tsconfig.json
  tests/e2e/yarn.lock
Labels: approved, lgtm, size/L

#426 feat(network): retry unconnectable consensus peer
  core/network/src/peer_manager/mod.rs
Labels: approved, lgtm, size/S

#412 fix(network): cannot process message after reactor exit
  core/network/examples/buycopy.rs
  core/network/src/lib.rs
  core/network/src/message/mod.rs
  core/network/src/outbound/gossip.rs
  core/network/src/outbound/rpc.rs
  core/network/src/protocols/core.rs
  core/network/src/protocols/transmitter.rs
  core/network/src/protocols/transmitter/protocol.rs
  core/network/src/reactor/mod.rs
  core/network/src/reactor/router.rs
  core/network/src/reactor/rpc_map.rs
  core/network/src/service.rs
  core/network/tests/gossip_test.rs
  src/default_start.rs
  tests/common/node/full_node/default_start.rs
  tests/trust_metric_all/client_node.rs
  tests/verify_chain_id.rs
Labels: approved, lgtm, size/XL

#425 fix(network): give up peer due to secio io error
  core/network/src/connection/keeper.rs
Labels: approved, lgtm, size/XS

#428 docs: Metrics docs for promethues
  common/apm/README.md
Labels: approved, lgtm, size/L

#430 fix(network): negative connecting metric number
  core/network/src/peer_manager/mod.rs
Labels: approved, lgtm, size/S

#429 feat(apm): add executing block num to apm
  common/apm/README.md
  common/apm/src/metrics/consensus.rs
  core/consensus/src/status.rs
Labels: approved, lgtm, size/S

#409 feat(test): Byzantine test
  Cargo.toml
  byzantine/Cargo.toml
  byzantine/README.md
  byzantine/generators.toml
  byzantine/resource/structure.png
  byzantine/src/behaviors.rs
  byzantine/src/commander.rs
  byzantine/src/config.rs
  byzantine/src/default_start.rs
  byzantine/src/invalid_types.rs
  byzantine/src/lib.rs
  byzantine/src/message.rs
  byzantine/src/strategy.rs
  byzantine/src/utils.rs
  byzantine/src/worker.rs
  core/mempool/src/adapter/message.rs
  core/mempool/src/lib.rs
  examples/byzantine_node.rs
  examples/config-2.toml
  examples/config-3.toml
  examples/config-4.toml
  protocol/src/traits/network.rs
  protocol/src/types/primitive.rs
Labels: approved, lgtm, size/XXL

#432 feat: log the overlord view change reason
  byzantine/Cargo.toml
  core/consensus/Cargo.toml
  core/consensus/src/engine.rs
  framework/Cargo.toml
Labels: approved, lgtm, size/L
